package com.example.a0708_kakaotest.Android_Class.menu_FragmentUse_Class;

import android.widget.ArrayAdapter;

import java.util.ArrayList;

public class Return_Citys_Array {

    public ArrayList<String> Market_cityArrayList(){
        ArrayList cityArrayList = new ArrayList<String>();
        cityArrayList.add("시/도");
        cityArrayList.add("대구광역시");
        cityArrayList.add("강원도");
        cityArrayList.add("경기도");
        cityArrayList.add("울산광역시");
        cityArrayList.add("서울특별시");
        cityArrayList.add("충청북도");
        cityArrayList.add("부산광역시");
        cityArrayList.add("전라남도");
        cityArrayList.add("충청남도");
        cityArrayList.add("경상북도");
        cityArrayList.add("전라북도");
        cityArrayList.add("인천광역시");
        cityArrayList.add("대전광역시");
        cityArrayList.add("경상남도");
        cityArrayList.add("광주광역시");
        cityArrayList.add("제주특별자치도");
        cityArrayList.add("세종특별자치시");
        return cityArrayList;
    }

    public ArrayList<String> Market_DisArrayList(String city){
        ArrayList disArrayList = new ArrayList<String>();
        disArrayList.add("시/군/구");
        if(city.equals("서울특별시")){
            disArrayList.add("관악구");
            disArrayList.add("동작구");
            disArrayList.add("송파구");
            disArrayList.add("금천구");
            disArrayList.add("양천구");
            disArrayList.add("동대문구");
            disArrayList.add("용산구");
            disArrayList.add("중랑구");
            disArrayList.add("성동구");
            disArrayList.add("도봉구");
            disArrayList.add("은평구");
            disArrayList.add("영등포구");
            disArrayList.add("광진구");
            disArrayList.add("마포구");
            disArrayList.add("구로구");
            disArrayList.add("성북구");
            disArrayList.add("중구");
            disArrayList.add("강북구");
            disArrayList.add("노원구");
            disArrayList.add("종로구");
            disArrayList.add("서대문구");
            disArrayList.add("강서구");
            disArrayList.add("강남구");
            disArrayList.add("강동구");
        }
        else if(city.equals("경기도")){
            disArrayList.add("오산시");
            disArrayList.add("평택시");
            disArrayList.add("이천시");
            disArrayList.add("수원시");
            disArrayList.add("구리시");
            disArrayList.add("양평군");
            disArrayList.add("의왕시");
            disArrayList.add("성남시");
            disArrayList.add("광주시");
            disArrayList.add("하남시");
            disArrayList.add("시흥시");
            disArrayList.add("김포시");
            disArrayList.add("안성시");
            disArrayList.add("화성시");
            disArrayList.add("의정부시");
            disArrayList.add("파주시");
            disArrayList.add("남양주시");
            disArrayList.add("동두천시");
            disArrayList.add("포천시");
            disArrayList.add("연천군");
            disArrayList.add("고양시");
            disArrayList.add("가평군");
            disArrayList.add("안산시");
            disArrayList.add("부천시");
            disArrayList.add("광명시");
            disArrayList.add("안양시");
            disArrayList.add("과천시");
            disArrayList.add("용인시");
            disArrayList.add("군포시");
            disArrayList.add("여주시");
        }
        else if(city.equals("인천광역시")){
            disArrayList.add("강화군");
            disArrayList.add("남동구");
            disArrayList.add("중구");
            disArrayList.add("계양구");
            disArrayList.add("동구");
            disArrayList.add("서구");
            disArrayList.add("부평구");
            disArrayList.add("미추홀구");
            disArrayList.add("연수구");
        }
        else if(city.equals("강원도")){
            disArrayList.add("태백시");
            disArrayList.add("삼척시");
            disArrayList.add("정선군");
            disArrayList.add("춘천시");
            disArrayList.add("속초시");
            disArrayList.add("인제군");
            disArrayList.add("홍천군");
            disArrayList.add("동해시");
            disArrayList.add("강릉시");
            disArrayList.add("평창군");
            disArrayList.add("양양군");
            disArrayList.add("양구군");
            disArrayList.add("철원군");
            disArrayList.add("고성군");
            disArrayList.add("원주시");
            disArrayList.add("영월군");
            disArrayList.add("횡성군");
            disArrayList.add("화천군");
        }
        else if(city.equals("충청남도")){
            disArrayList.add("태안군");
            disArrayList.add("서산시");
            disArrayList.add("청양군");
            disArrayList.add("금산군");
            disArrayList.add("논산시");
            disArrayList.add("서천군");
            disArrayList.add("천안시");
            disArrayList.add("당진시");
            disArrayList.add("아산시");
            disArrayList.add("공주시");
            disArrayList.add("보령시");
            disArrayList.add("예산군");
            disArrayList.add("홍성군");
            disArrayList.add("부여군");
        }
        else if(city.equals("대전광역시")){
            disArrayList.add("동구");
            disArrayList.add("서구");
            disArrayList.add("대덕구");
            disArrayList.add("유성구");
            disArrayList.add("중구");
        }
        else if(city.equals("충청북도")){
            disArrayList.add("제천시");
            disArrayList.add("음성군");
            disArrayList.add("충주시");
            disArrayList.add("청주시");
            disArrayList.add("단양군");
            disArrayList.add("괴산군");
            disArrayList.add("진천군");
            disArrayList.add("증평군");
            disArrayList.add("영동군");
            disArrayList.add("옥천군");
            disArrayList.add("보은군");
        }
        else if(city.equals("부산광역시")){
            disArrayList.add("중구");
            disArrayList.add("사상구");
            disArrayList.add("강서구");
            disArrayList.add("연제구");
            disArrayList.add("사하구");
            disArrayList.add("해운대구");
            disArrayList.add("남구");
            disArrayList.add("부산진구");
            disArrayList.add("수영구");
            disArrayList.add("동래구");
            disArrayList.add("북구");
            disArrayList.add("금정구");
            disArrayList.add("기장군");
            disArrayList.add("동구");
            disArrayList.add("서구");
            disArrayList.add("영도구");
        }
        else if(city.equals("울산광역시")){
            disArrayList.add("울주군");
            disArrayList.add("남구");
            disArrayList.add("중구");
            disArrayList.add("북구");
            disArrayList.add("동구");
        }
        else if(city.equals("대구광역시")){
            disArrayList.add("수성구");
            disArrayList.add("중구");
            disArrayList.add("동구");
            disArrayList.add("달서구");
            disArrayList.add("달성군");
            disArrayList.add("남구");
            disArrayList.add("북구");
            disArrayList.add("서구");
        }
        else if(city.equals("경상북도")){
            disArrayList.add("문경시");
            disArrayList.add("군위군");
            disArrayList.add("울진군");
            disArrayList.add("봉화군");
            disArrayList.add("안동시");
            disArrayList.add("성주군");
            disArrayList.add("경주시");
            disArrayList.add("경산시");
            disArrayList.add("고령군");
            disArrayList.add("영주시");
            disArrayList.add("예천군");
            disArrayList.add("포항시");
            disArrayList.add("김천시");
            disArrayList.add("청도군");
            disArrayList.add("상주시");
            disArrayList.add("영양군");
            disArrayList.add("의성군");
            disArrayList.add("청송군");
            disArrayList.add("구미시");
            disArrayList.add("영천시");
            disArrayList.add("영덕군");
            disArrayList.add("칠곡군");
        }
        else if(city.equals("경상남도")){
            disArrayList.add("양산시");
            disArrayList.add("거창군");
            disArrayList.add("창원시");
            disArrayList.add("거제시");
            disArrayList.add("남해군");
            disArrayList.add("통영시");
            disArrayList.add("진주시");
            disArrayList.add("김해시");
            disArrayList.add("함양군");
            disArrayList.add("함안군");
            disArrayList.add("의령군");
            disArrayList.add("밀양시");
            disArrayList.add("산청군");
            disArrayList.add("창녕군");
            disArrayList.add("고성군");
            disArrayList.add("합천군");
            disArrayList.add("하동군");
            disArrayList.add("사천시");
        }
        else if(city.equals("전라남도")){
            disArrayList.add("영광군");
            disArrayList.add("진도군");
            disArrayList.add("광양시");
            disArrayList.add("곡성군");
            disArrayList.add("화순군");
            disArrayList.add("여수시");
            disArrayList.add("완도군");
            disArrayList.add("해남군");
            disArrayList.add("장흥군");
            disArrayList.add("보성군");
            disArrayList.add("구례군");
            disArrayList.add("장성군");
            disArrayList.add("목포시");
            disArrayList.add("고흥군");
            disArrayList.add("영암군");
            disArrayList.add("무안군");
            disArrayList.add("함평군");
            disArrayList.add("담양군");
            disArrayList.add("나주시");
            disArrayList.add("순천시");
            disArrayList.add("강진군");
        }
        else if(city.equals("광주광역시")){
            disArrayList.add("동구");
            disArrayList.add("서구");
            disArrayList.add("북구");
            disArrayList.add("광산구");
            disArrayList.add("남구");
        }
        else if(city.equals("전라북도")){
            disArrayList.add("남원시");
            disArrayList.add("순창군");
            disArrayList.add("군산시");
            disArrayList.add("완주군");
            disArrayList.add("전주시");
            disArrayList.add("고창군");
            disArrayList.add("김제시");
            disArrayList.add("정읍시");
            disArrayList.add("진안군");
            disArrayList.add("부안군");
            disArrayList.add("익산시");
            disArrayList.add("임실군");
            disArrayList.add("장수군");
            disArrayList.add("무주군");
        }
        else if(city.equals("제주특별자치도")){
            disArrayList.add("제주시");
            disArrayList.add("서귀포시");
        }
        else if(city.equals("세종특별자치시")){
            disArrayList.add("전의면");
            disArrayList.add("부강면");
            disArrayList.add("조치원읍");
            disArrayList.add("금남면");
        }
        return disArrayList;
    }

    public ArrayList<String> Bank_cityArrayList() {
        ArrayList<String> cityArrayList = new ArrayList<String>();
        cityArrayList.add("시/도");
        cityArrayList.add("서울");
        cityArrayList.add("경기");
        cityArrayList.add("인천");
        cityArrayList.add("강원");
        cityArrayList.add("충남");
        cityArrayList.add("대전");
        cityArrayList.add("충북");
        cityArrayList.add("부산");
        cityArrayList.add("울산");
        cityArrayList.add("대구");
        cityArrayList.add("경북");
        cityArrayList.add("경남");
        cityArrayList.add("전남");
        cityArrayList.add("광주");
        cityArrayList.add("전북");
        cityArrayList.add("제주");
        cityArrayList.add("세종");
        return cityArrayList;
    }

    public ArrayList<String> Bank_DisArrayList(String city) {
        ArrayList<String> disArrayList = new ArrayList<String>();
        disArrayList.add("시/군/구");
        if(city.equals("서울")){
            disArrayList.add("강남구");
            disArrayList.add("강동구");
            disArrayList.add("강북구");
            disArrayList.add("강서구");
            disArrayList.add("관악구");
            disArrayList.add("광진구");
            disArrayList.add("구로구");
            disArrayList.add("금천구");
            disArrayList.add("노원구");
            disArrayList.add("도봉구");
            disArrayList.add("동대문구");
            disArrayList.add("동작구");
            disArrayList.add("마포구");
            disArrayList.add("서대문구");
            disArrayList.add("서초구");
            disArrayList.add("성동구");
            disArrayList.add("성북구");
            disArrayList.add("송파구");
            disArrayList.add("양천구");
            disArrayList.add("영등포구");
            disArrayList.add("용산구");
            disArrayList.add("은평구");
            disArrayList.add("종로구");
            disArrayList.add("중구");
            disArrayList.add("중랑구");

        }
        else if(city.equals("경기")){
            disArrayList.add("성남시");
            disArrayList.add("화성시");
            disArrayList.add("수원시");
            disArrayList.add("고양시");
            disArrayList.add("김포시");
            disArrayList.add("안양시");
            disArrayList.add("용인시");
            disArrayList.add("의정부시");
            disArrayList.add("평택시");
            disArrayList.add("안산시");
            disArrayList.add("구리시");
            disArrayList.add("광명시");
            disArrayList.add("시흥시");
            disArrayList.add("이천시");
            disArrayList.add("광주시");
            disArrayList.add("파주시");
            disArrayList.add("포천시");
            disArrayList.add("과천시");
            disArrayList.add("군포시");
            disArrayList.add("안성시");
            disArrayList.add("하남시");
            disArrayList.add("오산시");
            disArrayList.add("양주시");
            disArrayList.add("의왕시");
            disArrayList.add("남양주시");
            disArrayList.add("동두천시");
            disArrayList.add("부천시");
            disArrayList.add("여주군");
            disArrayList.add("연천군");
            disArrayList.add("가평군");
            disArrayList.add("양평군");
            disArrayList.add("분당구");
            disArrayList.add("여주시");
        }
        else if(city.equals("인천")){
            disArrayList.add("부평구");
            disArrayList.add("남동구");
            disArrayList.add("서구");
            disArrayList.add("중구");
            disArrayList.add("계양구");
            disArrayList.add("연수구");
            disArrayList.add("동구");
            disArrayList.add("강화군");
            disArrayList.add("남구");
            disArrayList.add("옹진군");
        }
        else if(city.equals("강원")){
            disArrayList.add("춘천시");
            disArrayList.add("강릉시");
            disArrayList.add("원주시");
            disArrayList.add("속초시");
            disArrayList.add("동해시");
            disArrayList.add("홍천군");
            disArrayList.add("횡성군");
            disArrayList.add("영월군");
            disArrayList.add("평창군");
            disArrayList.add("정선군");
            disArrayList.add("철원군");
            disArrayList.add("화천군");
            disArrayList.add("양구군");
            disArrayList.add("인제군");
            disArrayList.add("고성군");
            disArrayList.add("양양군");
            disArrayList.add("삼척시");
            disArrayList.add("태백시");
        }
        else if(city.equals("충남")){
            disArrayList.add("천안시");
            disArrayList.add("논산시");
            disArrayList.add("당진시");
            disArrayList.add("아산시");
            disArrayList.add("서산시");
            disArrayList.add("보령시");
            disArrayList.add("금산군");
            disArrayList.add("계룡시");
            disArrayList.add("공주시");
            disArrayList.add("부여군");
            disArrayList.add("서천군");
            disArrayList.add("청양군");
            disArrayList.add("홍성군");
            disArrayList.add("예산군");
            disArrayList.add("태안군");
            disArrayList.add("당진군");
            disArrayList.add("홍성시");
        }
        else if(city.equals("대전")){
            disArrayList.add("중구");
            disArrayList.add("서구");
            disArrayList.add("대덕구");
            disArrayList.add("동구");
            disArrayList.add("유성구");
        }
        else if(city.equals("충북")){
            disArrayList.add("청주시");
            disArrayList.add("충주시");
            disArrayList.add("제천시");
            disArrayList.add("청원구");
            disArrayList.add("음성군");
            disArrayList.add("옥천군");
            disArrayList.add("진천군");
            disArrayList.add("흥덕구");
            disArrayList.add("보은군");
            disArrayList.add("영동군");
            disArrayList.add("괴산군");
            disArrayList.add("증평군");
            disArrayList.add("단양군");
            disArrayList.add("상당구");
            disArrayList.add("서원구");
            disArrayList.add("청원군");
        }
        else if(city.equals("부산")){
            disArrayList.add("동구");
            disArrayList.add("사상구");
            disArrayList.add("동래구");
            disArrayList.add("강서구");
            disArrayList.add("해운대구");
            disArrayList.add("기장군");
            disArrayList.add("부산진구");
            disArrayList.add("사하구");
            disArrayList.add("중구");
            disArrayList.add("연제구");
            disArrayList.add("금정구");
            disArrayList.add("영도구");
            disArrayList.add("수영구");
            disArrayList.add("남구");
            disArrayList.add("북구");
            disArrayList.add("서구");
        }
        else if(city.equals("울산")){
            disArrayList.add("중구");
            disArrayList.add("남구");
            disArrayList.add("동구");
            disArrayList.add("울주군");
            disArrayList.add("북구");
        }
        else if(city.equals("대구")){
            disArrayList.add("중구");
            disArrayList.add("동구");
            disArrayList.add("서구");
            disArrayList.add("남구");
            disArrayList.add("북구");
            disArrayList.add("수성구");
            disArrayList.add("달서구");
            disArrayList.add("달성군");
        }
        else if(city.equals("경북")){
            disArrayList.add("구미시");
            disArrayList.add("포항시");
            disArrayList.add("경주시");
            disArrayList.add("영천시");
            disArrayList.add("안동시");
            disArrayList.add("경산시");
            disArrayList.add("김천시");
            disArrayList.add("영주시");
            disArrayList.add("칠곡군");
            disArrayList.add("군위군");
            disArrayList.add("의성군");
            disArrayList.add("청송군");
            disArrayList.add("영양군");
            disArrayList.add("영덕군");
            disArrayList.add("청도군");
            disArrayList.add("고령군");
            disArrayList.add("성주군");
            disArrayList.add("상주시");
            disArrayList.add("문경시");
            disArrayList.add("예천군");
            disArrayList.add("봉화군");
            disArrayList.add("울진군");
            disArrayList.add("울릉군");
        }
        else if(city.equals("경남")){
            disArrayList.add("창원시");
            disArrayList.add("진주시");
            disArrayList.add("통영시");
            disArrayList.add("사천시");
            disArrayList.add("고성군");
            disArrayList.add("거창군");
            disArrayList.add("밀양시");
            disArrayList.add("양산시");
            disArrayList.add("거제시");
            disArrayList.add("창녕군");
            disArrayList.add("남해군");
            disArrayList.add("김해시");
            disArrayList.add("함안군");
            disArrayList.add("합천군");
            disArrayList.add("의령군");
            disArrayList.add("함양군");
            disArrayList.add("산청군");
            disArrayList.add("하동군");
            disArrayList.add("마산시");
            disArrayList.add("진해시");
            disArrayList.add("중구");
            disArrayList.add("남구");
        }
        else if(city.equals("전남")){
            disArrayList.add("강진군");
            disArrayList.add("고흥군");
            disArrayList.add("광양시");
            disArrayList.add("나주시");
            disArrayList.add("순천시");
            disArrayList.add("무안군");
            disArrayList.add("담양군");
            disArrayList.add("영암군");
            disArrayList.add("목포시");
            disArrayList.add("보성군");
            disArrayList.add("여수시");
            disArrayList.add("영광군");
            disArrayList.add("완도군");
            disArrayList.add("장성군");
            disArrayList.add("장흥군");
            disArrayList.add("함평군");
            disArrayList.add("해남군");
            disArrayList.add("화순군");
            disArrayList.add("곡성군");
            disArrayList.add("구례군");
            disArrayList.add("진도군");
            disArrayList.add("신안군");
        }
        else if(city.equals("광주")){
            disArrayList.add("북구");
            disArrayList.add("동구");
            disArrayList.add("서구");
            disArrayList.add("남구");
            disArrayList.add("광산구");
        }
        else if(city.equals("전북")){
            disArrayList.add("군산시");
            disArrayList.add("전주시");
            disArrayList.add("익산시");
            disArrayList.add("정읍시");
            disArrayList.add("남원시");
            disArrayList.add("진안군");
            disArrayList.add("무주군");
            disArrayList.add("장수군");
            disArrayList.add("임실군");
            disArrayList.add("순창군");
            disArrayList.add("고창군");
            disArrayList.add("부안군");
            disArrayList.add("김제시");
            disArrayList.add("완주군");
        }
        else if(city.equals("제주")){
            disArrayList.add("제주시");
            disArrayList.add("서귀포시");
        }
        else if(city.equals("세종")){
            disArrayList.add("세종시");
        }

        return disArrayList;
    }
    public  ArrayList<String> Bank_ArrayListinit(){
        ArrayList<String> bankList = new ArrayList<String>();
        bankList.add("은행");
        bankList.add("신한은행");
        bankList.add("우리은행");
        bankList.add("국민은행");
        bankList.add("대구은행");
        bankList.add("부산은행");
        bankList.add("광주은행");
        bankList.add("전북은행");
        bankList.add("경남은행");
        bankList.add("수협");
        bankList.add("신협");
        bankList.add("농협");
        bankList.add("우체국");
        bankList.add("새마을금고");
        bankList.add("IBK기업은행");
        return bankList;
    }
}
